<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>info</string>
	</array>
	<key>name</key>
	<string>Drupal Info File</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.name</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^([a-zA-Z0-9_\]\[]+)\s*=\s*(.+)$</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^;.+</string>
			<key>name</key>
			<string>comment</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.drupal.info</string>
	<key>uuid</key>
	<string>67da56ca-6afb-4130-b717-d339d4a854b6</string>
</dict>
</plist>
